### ISSUE TITLE
Switch master language to EN

### ISSUE THREAD

**Issue by christianguenter2** [keremkoseoglu/ticksys#9]
Switch master language to EN would ease things a bit for potential users. Same for prerequisite repos.
https://github.com/keremkoseoglu/ticksys/blob/441181c9239d93f063a3e256bece338d12eab814/.abapgit.xml#L5

**Comment by keremkoseoglu** [comment]
Hello @christianguenter2 ; all of my source ABAP Systems are in master language T. I tried turning abapgit.xml to E before, but that prevented me from pushing ABAP code to GitHub from my "T" systems.

If you have a solution, please share.

**Comment by christianguenter2** [comment]
Do you have language `E` also installed? If not it won't be possible. If yes, you have to commit further changes while logged on in English. Do you get an error message?

**Comment by keremkoseoglu** [comment]
I checked my source systems. I'm afraid I won't be able to do this switch at this time. But you are more than welcome to make a fork and change the language, @christianguenter2  .
